### ISSUE TITLE
Consensus needed to deprecate HC terms related to "size class"

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#10]
Two terms in original HC refer to size class:

- Original HC `size class` (currently `sizeClassScope` in IPT) definition:
   > Size classes included in the study for the prospective taxa (e.g., only small mammals).
  - examples provided with HC paper: `medium to larger mammals for camera traps`, `nets mesh small enough for small arctic fish`

- Original HC `size class excluded` (currently `excludedSizeClassScope` in IPT) definition:
   > Size classes excluded in the study for the prospective taxa (e.g., only small mammals).
  - examples provided with HC paper: `live trapping exluded larger mammals`

\
During first round of review we identified the following issues with this term:
- As for the examples provided, this term is actually mixing sizes with taxonomic scope, sampling method and geographic scope.
- A size class that was populated with "small / medium / large" is ambiguous enough that it would probably not really serve any purpose.

So we request input on whether to:
1. **deprecate** this term; or
2. turn it into a numeric field - which should probably allow for ranges - e.g., sizeInXXXXScope (in what? would this be length? volume? other? could it really be estimated? how often would this kind of info be reported to justify having a term for it?)

**Comment by tucotuco** [comment]
Since the apparent intended usage of these concepts is broad and vague, how does it serve anyone that wouldn't be served by just relegating this information to dwc:samplingProtocol or dwc:eventRemarks? I would recommend deprecating these.

**Comment by pzermoglio** [comment]
Following group discussions from 2021-06-09, both terms are to be DEPRECATED.
