### ISSUE TITLE
Need to add comments or examples to dwc:samplingEffort?

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#11]
Currently `dwc:samplingEffort`:
![image](https://user-images.githubusercontent.com/9394433/109378579-7a854c00-78b2-11eb-94d0-b1d117b0dcad.png)

Would there be any suggestions for addition of comments or examples to the DwC term?
E.g., "In the case of summary inventories / compilations... you should report... bla".

**Comment by tucotuco** [comment]
This is related to decisions for Issue #9 and Issue #10. Comments and further examples will not require public review as long as they do not conflict with the current semantics of the term.

**Comment by tucotuco** [comment]
This proposal was not acted upon prior to the Humboldt Extension public review.
