### ISSUE TITLE
Need general discussion on HC term effortCalculatedBy

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#12]
Original HC term is: `effort calculated by author or by data entry person?`
(current `effortCalculatedBy`)
with definition:
>Was the final assessment of effort reported directly by author or an assessment by data entry person?

\
During first round of review we considered that the goal of this term may be understood in two different ways. For each possibility, we thought of definitions etc. 

1. what is important is whether the effort was inferred or originally reported
If so, propose to change definition to:
    >A statement about whether effort associated with the sampling event(s) was originally reported or inferred.

    with controlled vocabulary expected, and examples:  `effortOriginallyReported`, `effortInferred`

2. what is important is the actual agent who calculated the effort - or her/his role.
If so, propose to center in the roles and not in the names of the agents, and change definition to:
    >The role of the agent responsible for reporting the effort associated with the sampling event(s) referred to in the record.

    with controlled vocabulary expected, and examples: `dataEntryPerson`, `surveyAuthor`, `collector`

\
_Note on the term name:_
In DwC, all terms of the shape XXXXBy expect a list of names of people/orgs. Here it seems we do not expect such list, but rather either reported vs inferred or the people's roles. Would need to change term name in any case.

\
**Input requested from everyone about this term.**

**Comment by yanisica** [comment]
Comments from Peter Brenton:

effortCalculatedBy: "Not sure about the value of this. How would it be expected to be applied?"

See more info here on HC - PPSR mapping [here](https://docs.google.com/spreadsheets/d/1k2Pi02f6vBmkOdulzzUXKsKVFjbkyI-p/edit#gid=772770851)

**Comment by tucotuco** [comment]
I'm not sure of the utility of this either, but if it is deemed important, would it not be sufficient to use the usual Darwin Core pattern and actually name the person? If it is the same as the author, the author did it. If it isn't the same as the author, it was somewhere else in the workflow and we would even know who it was. If this is acceptable, then a term effortCalculatedBy would be fine and could be defined using the usual pattern.

"A list (concatenated and separated) of names of people, groups, organizations, or software responsible for calculating the samplingEffort."

I threw the "or software" in there on a whim.

**Comment by tucotuco** [comment]
The Extension proposal ended up not including this term.
