### ISSUE TITLE
Need general discussion HC term 'recording or measurement agent type'

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#13]
Original HC term `recording or measurement agent type` definition:
>The agent taking the recording.  This can be "human" or   "machine" (e.g., camera traps)

(examples wrongly and only included in definition above).

This term can be tricky. It may be kept "simple" if we only want to denote if it was human or machine taking the record (?). But a more complicated path can be considered, in relation with definition/use of `basisOfRecord`. I'll list here just some considerations:

- The Event Core does not include the term basisOfRecord. [basisOfRecord](https://dwc.tdwg.org/terms/#dwc:basisOfRecord) allows values that are the DwC classes (including "Event"), and therefore the term is probably not included in the Event Core because it would be redundant. 
- However, an event can be of other of the "bases" (e.g., MachineObservation, HumanObservation, etc.).
- Including basisOfRecord in the extension could be considered, but how would we not default it to value "Event"?
- basisOfRecord does not currently have an ontology behind it.
- Note that even though recommended vocab are the DwC classes, other values are currently in broad use, e.g., Literature and Unknown (see [GBIF basisOfRecord vocab](https://gbif.github.io/parsers/apidocs/org/gbif/api/vocabulary/BasisOfRecord.html))
- For a long, thorough discussion on basisOfRecord see [issue #302 in the DwC repo](https://github.com/tdwg/dwc/issues/302).

As from the first review round, we identified 3 possible routes to follow:
1. Keep this term in the HC extension but in a very simple way, something that basically would only indicate if a camera trap was involved. This would have to be done carefully to not confuse with basisOfRecord as current, and would probably overlap with sampling protocol.

2. Deal with basisOfRecord once and for all, for DwC in general. This would mean reviewing its definition, probably defining an ontology, etc. LONG process, with many challenges, but probably many BIG gains all over.

3. Propose a term within the HC extension that would momentarily take care of the issue, and which could be deprecated in the future when the basisOfRecord big issue is resolved. For this option a proposal is to create a `basisOfEvent` term, with definition in the lines of:
      >The nature of the sampling event(s) referred to in the record, regarding the type of agent that performed the sampling.

### <div align="center">:eyes:Insights needed!

**Comment by tucotuco** [comment]
For practical plus forward-pointing reasons, I like option 3. I don't think
this Task Group should have to solve or wait on the bigger issue.

**Comment by timrobertson100** [comment]
I agree that avoiding `basisOfRecord` is a sensible way to be able to progress this. 

I wonder if we might want to consider alternatives to `basisOfEvent`? I suspect `basisOfRecord` was misunderstood because it was so generic and we might be repeating previous mistakes.

If the intention is to capture the type of "thing" creating the samples or measurements perhaps we should be specific in that; such as `typeOfRecorder` with a controlled vocabulary (camera trap, human, radar, laser, microphone etc)?

**Comment by tucotuco** [comment]
The term dwc:eventType, organized in the dwc:Event class, has been added to Darwin Core.
