### ISSUE TITLE
HC terms that map to EML

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#14]
There are 3 original HC terms that after first review round we are proposing to map to EML:

1. `metadata recorder`, original definition:
   > Names of the data entry recorders and validators for this dataset.

   suggested mapping route: eml:dataset/associatedParty and eml:dataset/associatedParty/role

2. `metadata reviewer`, original definition:
   > Names of those reviewing entries during a QA/QC process.

   suggested mapping route: eml:dataset/associatedParty and eml:dataset/associatedParty/role

3. `quality assurance procedure`, original definition:
   >A list of any data quality procedures that were reported by the inventory authors.

   suggested mapping route: eml:dataset/methods/qualityControl

See references here: 
[general eml-dataset terms](https://eml.ecoinformatics.org/schema/eml-dataset_xsd.html)
[associatedParty](https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_associatedParty)
[role](https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_ResourceGroup_associatedParty_role)

While in the context of IPT providing this information would be relatively simple, there has been concern about how others, not using IPT, would/should share this information in an EML document (e.g., will they know how to do it). Fear is that without having specific HC terms to capture this information people will not report it. I'd argue that this will be the case for any metadata-related piece of information, and that this constitutes a matter of providing some guidelines rather than adding terms that already exist. 

### **<div align="center">:blue_book::pencil:This may be a topic for the documentation</div>**

**Comment by tucotuco** [comment]
I agree with the proposed solution. These data are at the dataset level and the Darwin Core solution to that already exists. Since we are posing HC as a Darwin Core extension and not a standard on its own, it would be hard to justify creating new terms that do the same thing as existing ones.

**Comment by tucotuco** [comment]
None of these terms were proposed for the Humboldt Extension public review.
