### ISSUE TITLE
Geospatial scope and area sampled -related terms

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#15]
The following three terms in HC are related to "geospatial scope" and area sampled, we would need everyone's input to agree on decisions to take:

1. Original HC `geospatial scope` definition:
   > The region of the inventory as described in text form (e.g. "Kruger National Park" or "Alberta").

   - This term is currently not included (deprecated) as it would/should be described using the various Location terms already available in the Event Core.

   :question: Is there agreement in this?

2. Original HC `total area covered by geospatial scope` definition:
   > Author's reported total area of the geospatial scope in km2.
    
    - current `geospatialScopeAreaInSquareKilometers`
    - updated definition proposed: 
       > Total area in km2 of the sampling event(s)' geospatial scope.
    - with comments: 
       > This area is always greater than or equal to totalAreaSampledInSquareKilometers.
    - with examples: `25`

   :question: We would be referring here to a geospatial scope that is not defined anywhere as such (term above deprecated). How can we tweak the definition of this one?

3. Original HC `total area covered by species inventory` definition:
   >Author's reported total area covered by effort to inventory species in km2 (always less than or equal to "geospatial scope" term above.

  - current `totalAreaSampledInSquareKilometers`
    - updated definition proposed: 
       > Reported total area in km2 covered by the sampling event(s) contributing to the one referred to in the record.
    - with comments: 
       > This area is always less than or equal to geospatialScopeAreaInSquareKilometers.
    - with examples: `0.8`

  - Notes: 
    - There are two terms already in DwC that could capture area info, `sampleSizeValue` and `sampleSizeUnit`. However, definition of `sampleSizeValue` includes more than geospatial:
      > A numeric value for a measurement of the size (time duration, length, area, or volume) of a sample in a sampling event.
    - We therefore propose to keep it separate. 

    :question: Should there be specific recommendations on usage of `sampleSizeValue`?

**Comment by tucotuco** [comment]
I agree with the deprecation of **geospatial scope** in favor or already existing richness of Darwin Core Location terms. the geospatial scope would just be the Location as defined in the Event at whatever level in the hierarchy.

For 2., what about "Total area of the geographic area of interest of the inventory, in square kilometers."? With a comment explaining how this is different from the sampling area. Excuse my ignorance, but does this concept actually have a defensible use? If the geographic scope is just to give people an idea of where the inventory took place, it seems the area isn't particularly relevant. Can this term be deprecated? 

For 3., what about "Total area of the Location covered by the Event, in square kilometers."? With a comment explaining how this is different from the geographic scope, not just that it is always less than or equal in area.

About the Notes. If the area was the only sample size measure that would be of interest, it seems that dwc:sampleSizeValue and dwc:sampleSizeUnit could be used in place of totalAreaSampledInSquareKilometers without any problem if the recommendation was always to use square kilometers.

**Comment by tucotuco** [comment]
The Extension proposal ended up including eco:geospatialScopeAreaInSquareKilometers and eco:totalAreaSampledInSquareKilometersProperty.
