### ISSUE TITLE
absentTaxa - Need general discussion on HC term

### ISSUE THREAD

**Issue by yanisica** [tdwg/hc#17]
During first round of review we considered keeping this as a HC term. 

Peter Brenton raised a question regarding the meaning of this information at the dataset level.  See more info here on HC - PPSR mapping [here](https://docs.google.com/spreadsheets/d/1k2Pi02f6vBmkOdulzzUXKsKVFjbkyI-p/edit#gid=772770851)

PB comment: I don't see the value in listing absent taxa. **Suggest not including this in HC as it is meaningless at aggregation (dataset) level.** In practice, recording of taxon absences will be done at the event level as individualCount=0 and generally only when the recorder is specifically going to look for those taxa. For example, I could do a survey in the Australia desert and report that I didn't see an elephant and a whole bunch of other things that I wouldn't expect to finf there on that survey, but what is the point? it is meaningless information. I could also go there and report that I didn't see a camel - this may or may not be relevant depending on whether I was actually looking for camels or not. It would be fine to report that I didn't see a camel on that visit, but that would also be true of thousands of other taxa that I wouldn't report, so event data would be skewed and imply that what wasn't reported wasn't there becuse it wasn't expected to be there anyway, when in reality it may have been there, but just not reported because I wasn't looking for that thing.

| Field | Value |
| ----- | ----- |
| **HC term name** |  absentTaxa |
| **DwC-style term name** | absentTaxa  |
| **HC description** (HC original definition) | List of taxa reported absence(s) at whatever taxonomic level reported  |
| **Definition** | A list (concatenated and separated) of taxa reported absent during the sampling event(s) referred to in the record.  |
| **Comments** |  Absences could be   reported at any taxonomic level. Recommended best practice is to separate the   values in a list with space vertical bar space ( \| ). |
| **Examples** |   |
| **References** |   |
| **Discussion summary** | *[reserved to capture important outcomes of discussions to avoid having to read all over again!]* |
| **Mappings** | *PPSR: Observation Model - Environmental Sciences/Agriculture & vetinery Sciences domains as dwc:scientificName where dwc:individualCount = 0 *  |

*Note that HC description and Definition may be the same if no changes are suggested for the term. If changes are suggested, Definition will change but HC description should remain unaltered for reference.*

**Comment by robgur** [comment]
We should talk about this one.  Summary inventory authors often report
absences and it seems a shame to not collect that info if it is reported?

**Comment by tucotuco** [comment]
If a separate term was added to HC, it could only apply at the Event level, which as Peter pointed out could be problematic. The dwc:occurrenceStatus term (see Note below) applies to an Occurrence, which carries the Taxon information with it already. An absence of a Taxon could be reported on one Occurrence row. The "list" of absent taxa would be realized with multiple rows. Best practice would dictate that an absence Occurrence record would also contain the sampling protocol and effort information. It would not be expected to list absences of taxa that were not being sought.

Going this route, the challenge is when the range of taxa sought is large. For each Event, there would have to be an Occurrence record, with dwc:occurrenceStatus "present" or "absent", for each of the taxa in scope. 

An alternative might be to recommend another extension (TaxonScope?) to the Event Core in which each row is a target Taxon for detection. The Occurrence extension would contain all of the presences. Absences for a given Event would be determined from all taxa in the TaxonScope that do not have Occurrence records for the same Event.

Note: Though dwc:individualCount (or dwc:organismQuantity with dwc:organismQuantityType="individuals") could be used to express absence, that is not what I would recommend. The term dwc:occurrenceStatus is meant to capture absences explicitly. This term has a recommended controlled vocabulary of "present" and "absent" only.

**Comment by tucotuco** [comment]
The term absentTaxa was included in the Extension proposal.
