### ISSUE TITLE
effortCalculationProtocol - Need general discussion

### ISSUE THREAD

**Issue by yanisica** [tdwg/hc#18]
During first round of review we considered keeping this as a HC term.

Peter Brenton raised a question regarding the usefullness to keep it separate from samplingProtocol. See more info here on HC - PPSR mapping [here](https://docs.google.com/spreadsheets/d/1k2Pi02f6vBmkOdulzzUXKsKVFjbkyI-p/edit#gid=772770851)

Related to issue #12 

| Field | Value |
| ----- | ----- |
| **HC term name** | effortCalculationProtocol  |
| **DwC-style term name** | effortCalculationProtocol  |
| **HC description** (HC original definition) | If calculated, what data and what method were used to determine assessment of effort?  |
| **Definition** |  A description of   or reference to (publication, URI) the method or rationale used to determine   the sampling effort. |
| **Comments** | The sampling effort may be originally reported or inferred.  |
| **Examples** |  'summed from reporting of hours', 'summed time trawled'  |
| **References** |   |
| **Discussion summary** | *[reserved to capture important outcomes of discussions to avoid having to read all over again!]* |
| **Mappings** | *[equivalents in other standards]*  |

*Note that HC description and Definition may be the same if no changes are suggested for the term. If changes are suggested, Definition will change but HC description should remain unaltered for reference.*

**Comment by tucotuco** [comment]
If deemed worth keeping this concept, here is a provisional definition following the Darwin Core model.

"The name of, reference to, or description of the method or protocol used to calculate the samplingEffort."

**Comment by yanisica** [comment]
After many rounds of discussion, we landed on this definition and term name:

- term_localName = samplingEffortProtocol
- label = Sampling Effort Protocol
- definition = A description of or reference to (publication or URL) the method(s) used to determine the sampling effort.
- comments = This description should be associated with reporting of eco:samplingEffortValue and eco:samplingEffortUnit. This is a specialization of eco:protocolDescription focused on the effort as distinct from the survey method itself. The effort relates to the intensity of sampling and therefore can assist in interpreting measures of completeness.

**Comment by tucotuco** [comment]
The term eco:samplingEffortProtocol was included in the Extension proposal.
