### ISSUE TITLE
observation of specimen

### ISSUE THREAD

**Issue by neilcobb** [tdwg/hc#19]
| Field | Value |
| ----- | ----- |
| **HC term name** |   |
| **DwC-style term name** |  basisofRecord |
| **HC description** (HC original definition) |   |
| **Definition** |   |
| **Comments** |  we recently ran into a problem with uploading data to GBIF where the records were specimens identified under a dissecting scope and then tossed.  they are not the same observations as those in the field (e.g., iNat) but they are not vouchered specimens.  what should they be called? many ecological studies do this|
| **Examples** |   |
| **References** |   |
| **Discussion summary** | *[reserved to capture important outcomes of discussions to avoid having to read all over again!]* |
| **Mappings** | *[equivalents in other standards]*  |

*Note that HC description and Definition may be the same if no changes are suggested for the term. If changes are suggested, Definition will change but HC description should remain unaltered for reference.*

**Comment by tucotuco** [comment]
This did not factor in to the Extension proposal.

The situation is a common one. The solution is to create an Occurrence record with basisOfRecord PreservedSpecimen, but with disposition "discarded" or similar.
