### ISSUE TITLE
SamplingProtocol examples

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/hc#20]
Inspired by @pzermoglio's TDWG talk, I thought it might be useful to share all [the controlled `SamplingProtocol` values](https://github.com/BelgianBiodiversityPlatform/natagora-occurrences/blob/master/references/samplingProtocol.csv) we use for the Belgian citizen science datasets from [Natuurpunt](https://www.gbif.org/publisher/4d3ceea8-5699-439d-a899-decac9cbbdac) and [Natagora](https://www.gbif.org/dataset/629befd5-fb45-4365-95c4-d07e72479b37):

```
camera trap
casual observation
catch
catch and removed
catch by electrofishing
catch by fishermen
catch by fishing rod
catch by hand
catch by hand and collected
catch by hand and released
catch by net
catch by pod
catch by pole
catch by screen
catch by sheer
catch by shrimp net
catch by trawl net
colour trap
corrugated plate
deep drilling
DNA barcoding
heard
light trap
malaise trap
observation with bat detector
observation with flashlight
observation with hydrophone
pellet examination
pheromones bait
pitfall trap
seen
seen and heard
seen indoors
sheet with light
snorkeling observation
soil sample
sound trap
specimen collected
spotlight
sugar bait
telemetry searching
thermal imaging scope
track bed
unspecified trap
```

Welcome to close this issue if not useful or already addressed 😄.

PS @pzermoglio we also have controlled vocabs for [behavior](https://github.com/BelgianBiodiversityPlatform/natagora-occurrences/blob/master/references/behavior.csv), [occurrenceRemarks](https://github.com/BelgianBiodiversityPlatform/natagora-occurrences/blob/master/references/occurrenceRemarks.csv) and [reproductiveCondition](https://github.com/BelgianBiodiversityPlatform/natagora-occurrences/blob/master/references/reproductiveCondition.csv), but that is out of scope for HC.

**Comment by pzermoglio** [comment]
Thanks @peterdesmet! :blush:
We'll definitely take a good look at it.

re:other vocabs, yay! thanks! will include in the big list of available vocabs. :hugs:
