### ISSUE TITLE
url value for hc term targetTaxonomicScope 

### ISSUE THREAD

**Issue by ymgan** [tdwg/hc#22]
Hi @tucotuco 

During our meeting yesterday, we brought up a question from TDWG 2020 Working Session by @damianooldoni. The question is the possibility to have url field that points to a checklist for the field `targetTaxonomicScope`. 

The current recommendation for this field is multiple taxonomic names in a list with space vertical bar space ( | ). @baskaufs suggested to use the dwciri of this field for the url link to a species list. We are wondering how do we proceed with this? Do we need to provide an additional iri term to you to add this to IPT? Or does this happen automatically? (I am sorry, this is new to me) What do you think?

Thank you so much!

**Comment by tucotuco** [comment]
Hi @ymgan 

There are two part to the story. When the targetTaxonomicScope term is created, its dwciri counterpart will be created automatically (by the Darwin Core Maintenance Group). That part you need not worry about.

The other part, having it show up in the IPT, is another story. In general, the dwciri terms do not show up in the IPT. This has led to the minting of extra terms on occasion, specifically recordedByID and identifiedByID. I don't support the idea of creating extra terms this way, and would rather have dwciri terms possible to enable in the IPT, but that is perhaps a separate issue.

**Comment by tucotuco** [comment]
Will be covered by the creation of the ecoiri: equivalent of eco:targetTaxonomicScope.
