### ISSUE TITLE
Nit: reportedWeather example

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/hc#24]
Currently, the `reportedWeather` example reads as:
```
{'minimumTemperatureInDegreesFarenheit':18, 'maximumTemperatureInDegreesFarenheit':32, 'stillWaterCondition':'Partly Frozen'}
```

Is `stillWaterCondition` really weather? I would have anticipated heat, wind, cloudiness, rainfall etc, rather than assertions about the site or habitat itself.

**Comment by yanisica** [comment]
You are right, we will make sure to remove this example from reportedWeather.

**Comment by tucotuco** [comment]
The example for eco:reportedWeather was {"minimumTemperatureInDegreesFahrenheit": 18, "maximumTemperatureInDegreesFahrenheit": 32} in the Extension proposal.
