### ISSUE TITLE
JSON example should be double quoted

### ISSUE THREAD

**Issue by ymgan** [tdwg/hc#27]
Hi,

Thanks for the hard work! I spotted a minor thing, where I believe JSON example should be double quoted to be consistent with [dynamicProperties](https://dwc.tdwg.org/terms/#dwc:dynamicProperties) example

The example is at this line: 
https://github.com/tdwg/hc/blame/240e834e519e4e72d368e2dfadfc89b78280823e/docs/terms/index.md#L98

Thanks a lot!

**Comment by baskaufs** [comment]
Good catch, @ymgan . @tucotuco can you make sure this gets fixed in the raw metadata table update?

**Comment by tucotuco** [comment]
Addressed in [this commit](e25da4706f4f499eece32a8cbabf4d8cd2ba9009).
