### ISSUE TITLE
Explore Biocollect survey type vocabulary in the GBIF vocabulary server

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/hc#3]
The ALA biocollect tool has a working hierarchical vocabulary of survey types.
We should explore the feasibility and benefits of exporting this and creating a vocabulary in the GBIF vocabulary server.

**Comment by timrobertson100** [comment]
Reformating from [the email list](http://lists.tdwg.org/pipermail/tdwg-humboldt/2020-December/000000.html) I believe the protocols are as follows:

- Air quality
	- Fixed sensor
- Air quality 
	- Mobile sensor
- Bat survey
	- Echolocation recorder
	- Harp trapping
- Beach profile survey 
	- Emery method
	- Optical method
- Bird survey 
	- Distance sample (along transect)
	- Fixed-area
	- Fixed-time
	- Fixed-time & Fixed-area
	- Mist netting
- Fauna survey 
	- 2-Ha track plot method
	- Active search
	- Aerial distance sampler method
	- Cage trapping
	- Call playback
	- Camera trapping
	- Elliot trapping
	- Funnel trapping
	- Hair tubes
	- Nest box monitoring
	- Pitfall trapping
	- Scat survey
	- Spotlight search
	- Strip transect aerial survey
	- Turtle trapping
- Fish survey
	- Electrofishing
	- Set net/trap
	- Sweep netting
- Insect survey
	- Black light
	- Malaise trap
	- Baited trap
	- Glue trap
	- Sweep netting
- Plant propagation
	- Systematic seed propagation batch testing with different techniques
- Vegetation condition assessment 
	- Biocondition (QLD)
	- BioMetric (NSW)
	- Bushland Condition (SA)
	- Expert elicitation
	- Habitat Hectares (VIC)
	- LEBRA
	- TasVeg (TAS)
	- Post fire 
	- 	- Simple Photo Protocol
- Vegetation survey
	- General transect & plot
	- Step point method
- Water quality
	- Standardised physical/chemical attribute measurements
	- Macroinvertebrate survey 
	- 	- SIGNAL2 method
	- 	- ALT method
- Riparian condition assessment	
	- Rapid Appraisal of Riparian Condition (RARC)

**Comment by tucotuco** [comment]
@timrobertson100 Can this issue be closed?

**Comment by tucotuco** [comment]
Closed after confirmation from @timrobertson100 .
