### ISSUE TITLE
New Term - totalAreaSampledInSquareKilometers

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#33]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): totalAreaSampledInSquareKilometers
* Term label (English, not normative): Total Area Sampled In Square Kilometers
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): Total area surveyed during the dwc:Event in square kilometers.
* Usage comments (recommendations regarding content, etc., not normative): This area is always less than or equal to the geospatialScopeAreaInSquareKilometers.
* Examples (not normative): `0.8`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by kingenloff** [comment]
Feedback from colleagues at ALA: Including units in term names causes problems. It induces either over precise values or rounding errors. (Eg. is 1 mile 1.609344, 1.6 or 2 kilometres? The choice can lead to quite misleading results if multiple lengths are added together.) It’s also inconsistent with other terms, such as eventDuration and eventDurationUnit. 


Suggestion: separate into 2 terms, eco:totalAreaSampled and eco:totalAreaSampledUnit

**Comment by kingenloff** [comment]
The decision based on Task Group discussion is to be consistent and separate out the unit for everything. The rational will be explained in the implementation guide and the guide should recommend that a measurements and measurement units should always be a mandatory pair.
