### ISSUE TITLE
New Term - reportedWeather

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#34]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): reportedWeather
* Term label (English, not normative): Reported Weather
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): A list of weather or climatic conditions present during the dwc:Event.
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to use a key:value encoding schema for a data interchange format such as JSON.
* Examples (not normative): `{"minimumTemperatureInDegreesFahrenheit": 18, "maximumTemperatureInDegreesFahrenheit": 32}`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by kingenloff** [comment]
From our ALA colleagues: '**reportedWeather** and **reportedExtremeConditions** will tend to require embedded JSON to properly report. These could be MoFs [dwc:MeasurementOrFact (MoF) extension].'
