### ISSUE TITLE
Create a DwC-A sample using the HC extension from Biocollect

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/hc#4]
The GBIF test ipt.gbif.org has the draft HC extension.

We will identify a test dataset from Biocollect and map it in the IPT for presentation and training.

**Comment by tucotuco** [comment]
First pass ready at https://ipt.gbif.org/resource?r=act_waterwatch. Lacks full data set metadata. Needs Humboldt Extension to be linked and mapped. Both of these tasks are best done by the dataset provider.

**Comment by tucotuco** [comment]
This mapping was completed and is outdated as of the Humboldt Extension public review.
