### ISSUE TITLE
New Term - targetTaxonomicScope

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#40]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Needs ecoiri: equivalent in combination with eco:excludedTaxonomicScope.

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): targetTaxonomicScope
* Term label (English, not normative): Target Taxonomic Scope
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): The taxonomic group(s) targeted for sampling during the dwc:Event.
* Usage comments (recommendations regarding content, etc., not normative): The dwc:Event to which the eco:targetTaxonomicScope refers could be at any level of hierarchy. In the case of a higher level (parent) dwc:Event, include all taxonomic groups surveyed in the child dwc:Events that contributed to the parent dwc:Event. Recommended best practice is to separate multiple values in a list with space vertical bar space ( | ).
* Examples (not normative): `Aves`; `Aves | Mammalia`; `Procellariformes`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by tucotuco** [comment]
Would it be worth adding to the comments in scope terms such as this one that they SHOULD be populated only with scopes that were intended as part of the inventory design and SHOULD NOT be populated from the data that were reported? This is in the Event Hierarchy document, but it seems so critical for doing inferences properly that it might be worth having right there in the term metadata.

**Comment by WHochachka** [comment]
As long as the comments would not be viewed as overly long because of this addition, this makes sense to me.  I'm all in favour of including this sort of information as part of the information that defines and explains the terms.  I'm only mentioning the potential overly-longness, because I thought that at some point in the past, we were trying to keep comments as succinct as possible.

**Comment by tucotuco** [comment]
@WHochachka The issue with comment length had to do with comments long enough to require structure, such as paragraphs), which arose with the terms [dwc:verbatimLabel](https://dwc.tdwg.org/terms/#dwc:verbatimLabel) and [eco:isLeastSpecificTargetQuantityInclusive](https://eco.tdwg.org/terms/#eco:isLeastSpecificTargetCategoryQuantityInclusive). The accepted solution was to carry such extensive commentary into supplementary documentation referenced in the term comments. That too is an option for the comments proposed here, but it probably isn't necessary with the little extra I was suggesting.

**Comment by kingenloff** [comment]
From our ALA colleagues: 'The examples given for targetTaxonomicScope are broad taxa at the class level, such as Aves. This looks like broad, descriptive information, rather than a specific inventory of expected species. Having a more specific inventory would allow users to infer absences, even if we don’t do so ourselves. A taxonomicScopeType of, say, “descriptive” or “normative” would indicate the intended level of the scope.'

**Comment by WHochachka** [comment]
The comment by the ALA folks seems to suggest that they could not think of a use case in which it would be logical and appropriate to state a taxonomic scope as wide as Aves.  However, eBird represents exactly this use case.  When there is a parent event (birders would call this a "checklist") that does not contain a record of a species --- and that checklist is indicated to be a complete list of all species that were observed and identified, and there is the added constraint that only free-living and not escaped or captive organisms are being reported --- then any species of bird whatsoever is correctly inferred as not having been detected.  Sometimes this inference is trivial, for example Emu on Svalbard, but it is still a true inference.  As far as I can see, the statement is correct, and there would not be a need to change anything in response to this comment.
   However, perhaps this comment indicates that the relevant text should be adjusted to add the statement that the example of taxonomic scope reflects a real use case (e.g., eBird), and also add another example of where a more limited taxonomic scope than Aves would be necessary.  One such example could be the International Shorebird Survey (https://www.manomet.org/project/international-shorebird-survey/), although their data do not seem to be archived on GBIF or any other open-access archive.  Off the top of my head, I cannot think of any bird survey of limited taxonomic scope whose data are in an open-access archive.
