### ISSUE TITLE
New Term - taxonCompletenessReported

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#42]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Needs ecoiri: equivalent.

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): taxonCompletenessReported
* Term label (English, not normative): Target Completeness Reported
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): Statement about whether the taxonomic completeness of the dwc:Event was assessed.
* Usage comments (recommendations regarding content, etc., not normative): This term is meant to alert users that the inventory was conducted in such a way that all of the target taxa (the combination of eco:targetTaxonomicScope and eco:excludedTaxonomicScope) should have been detectable if they were present during the dwc:Event. This term can provide data users with a qualitative measure of how comprehensively an area has been surveyed, which assists in interpreting species populations, areas of occupancy, inferring species absences, etc. This term is only relevant if the dwc:Event used restricted search or open search methods. If taxonomic completeness was assessed, the methods used or an explanation of the basis of the completeness should be stated in eco: taxonCompletenessProtocols. Recommended best practice is to use controlled value strings from the controlled vocabulary designated for use with this term, listed at https://eco.tdwg.org/tcr/. This term has an equivalent in the dwciri: namespace that allows only an IRI as a value, whereas this term allows for any string literal value.
* Examples (not normative): `notReported`; `reportedComplete`; `reportedIncomplete`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by timrobertson100** [comment]
A really good addition to this would be to define the recommended vocabulary formally. As the usage comments describe, this field is fundamental for any consumer to confidently interpret the counts, infer absence of detection etc. Without control, every dataset will need to be handled individually.

I don't think this should block any progress, but perhaps could be discussed in the task group. If it is as simple as the 3 examples we could add them in the DwC-A extension during this review period.

**Comment by baskaufs** [comment]
I've created the [spreadsheet for generating the controlled vocabulary](https://github.com/tdwg/hc/blob/taxonCompletenessReportedCV/build/txcmrp_cv/taxonCompletenessReported_cv.csv). 

In the spreadsheet, I differentiated between the English labels (in prose) and the controlled value strings that we want people to use: in lowerCamelCase following the convention used in other controlled vocabularies. 

All that the spreadsheet is lacking is the definitions for the three values. The other columns can be ignored. If someone can fill in the definitions, I can generate the list of terms doc for it. Eventually, we will want to translate the labels and definitions into languages other than English, but for now this would get us to the proposal stage. 

I put the draft in a branch so that it wouldn't trigger rebuilding the website every time we push to it.

Ping @tucotuco @timrobertson100 @yanisica

**Comment by baskaufs** [comment]
The formal controlled vocabulary has been generated and is at <https://eco.tdwg.org/tcr/>. Please look it over. 

If this is acceptable, we need to change the term metadata to match what we've done with the other controlled vocabularies. See [this](https://dwc.tdwg.org/list/#dwc_establishmentMeans) for an example.

Also, to follow previous conventions, the controlled values are in lowerCamelCase, so the examples should be changed accordingly.

**Comment by tucotuco** [comment]
I updated the first comment to reflect the specific recommended controlled vocabulary for this term.

**Comment by tucotuco** [comment]
For the definition of http://rs.tdwg.org/ecotcr/values/tcr, I recommend "A SKOS Concept Scheme to be used as a controlled vocabulary for the term eco:taxonCompletenessReported."

**Comment by kingenloff** [comment]
From our ALA colleagues: 'Should targetCompletenessReported allow a measure, such as “50%” rather than a vocabulary term?'

**Comment by baskaufs** [comment]
During discussion on 2023-11-29: the use case that underlies this term was eBird, where people either are reporting complete lists of everything they saw or not. In that case, any value other than reportedComplete means that the data can't be used for quantitative calculations. So it doesn't really matter what the percent is if it is something other than 100%. One could report a percent, but how would anyone actually make use of it? Our conclusion was that we should leave the values as they are.
