### ISSUE TITLE
New Term - identifiedBy

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#56]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Needs ecoiri: equivalent.

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): identifiedBy
* Term label (English, not normative): Identified By
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): A list (concatenated and separated) of names of people, groups, or organizations who assigned the dwc:Taxon to the subject.
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to separate multiple values in a list with space vertical bar space ( | ).
* Examples (not normative): `James L. Patton`; `Theodore Pappenfuss | Robert Macey`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/Identifications/Identification/Identifiers/IdentifiersText

**Comment by nielsklazenga** [comment]
Is this a new term, or is it the existing http://rs.tdwg.org/dwc/terms/identifiedBy? The definition is the same.

**Comment by tucotuco** [comment]
This is anew term in the eco: namespace an applies at the level of a dwc:Event. The same with eco:identificationReferences.

**Comment by nielsklazenga** [comment]
Any reason why dwc:identifiedBy cannot be used at the event level? Mind you, I am not objecting, just trying to understand. I am presuming dwc:identifiedBy is at the level of a dwc:Occurrence, but I do not understand the difference in this context. I guess I am just looking for an example of a situation where the two are different.

**Comment by nielsklazenga** [comment]
Just found an example in the Usage Guide:

> 1.  dwc:eventID: BROKE_WEST_RMT_006
> Anton Van de Putte recorded (samplingPerformedBy) and identified (identifiedBy) the catch from the target trawl sampling Event. 

Clearly a different thing, but the definition is misleading, as the subject is the sample and that is cannot always be assigned to a single dwc:Taxon. I think a different definition is required and perhaps a different local name.

**Comment by tucotuco** [comment]
The context for the usage here is that all of the Identifications of dwc:Organisms within a dwc:Event were done by the agent given in eco:identifiedBy. It is needed at the dwc:Event level for cases where there are absences or eco:excludedTaxa that would not show up in related dwc:Occurrences (an agent made a determination that no dwc:Organisms of a given dwc:Taxon were detected). That in itself doesn't mean that eco:identifiedBy is different from dwc:identifiedBy, it just serves a purpose that dwc:identifiedBy can't serve if it must be a property of a dwc:Occurrence. Since property assignment in Darwin Core is only organizational, that doesn't mean that eco:identifiedBy is different from dwc:identifiedBy either. They are effectively the same, with one applied to dwc:Events and one applied to dwc:Occurrences. I believe that the rationale here is to avoid confusing the two uses as there are currently no semantics to define a dwc:Occurrence as a special kind of dwc:Event.

**Comment by tucotuco** [comment]
> Just found an example in the Usage Guide:
> 
> > 1. dwc:eventID: BROKE_WEST_RMT_006
> >    Anton Van de Putte recorded (samplingPerformedBy) and identified (identifiedBy) the catch from the target trawl sampling Event.
> 
> Clearly a different thing, but the definition is misleading, as the subject is the sample and that cannot always be assigned to a single dwc:Taxon. I think a different definition is required and perhaps a different local name.

Specific recommendations are very welcome.

**Comment by nielsklazenga** [comment]
Thanks for the explanation @tucotuco. I can have a think about the definition but just adding the first part of your explanation above as a comment to the term will do the trick I reckon.

**Comment by tucotuco** [comment]
If that IS sufficient it is a nice solution. Thanks @nielsklazenga for the extra eyes on this. The Task Group's eyes (I include mine here) may have glazed over after three years of looking at these terms. ;-)

**Comment by timrobertson100** [comment]
@tucotuco - can you see any reasonable solution that would reuse the existing DwC term or is it simply unpractical, please? 

Given DwC only provides a loose grouping of terms rather than providing a strict semantic model, is it problematic that a DwC term from the `Identification` group (not Occurrence) be used on an `eco:Event`? It seems a shame to mint and govern the exact same term in a different namespace. Note that identifiedByID would also be affected if that were to be introduced in HC.

Thanks. 

(My comment is only intended to check options have been explored, not try and block progress)

**Comment by tucotuco** [comment]
@timrobertson100 With Darwin Core we have the luxury of undefined semantics. By this I mean that, though we organize dwc:identifiedBy under the dwc:Identification Class, that organization has no binding meaning. That leaves us free to have a dwc:Identification of a dwc:Occurrence, or of a dwc:Event, or of a dwc:Organism or of (the dwc:Organisms associated with) a dwc:Event. This would change if a semantic layer on top of the Darwin Core "bag of terms" were implemented saying, for example, that a dwc:Identification is always made on a dwc:Organism, but that is not currently the case and would require a more fully described structure to the data.

The relevant technical question right now is probably, "Does eco:identifiedBy actually mean something different, on its own, from dwc:identifiedBy?" Their definitions are identical, "A list (concatenated and separated) of names of people, groups, or organizations who assigned the dwc:Taxon to the subject." "Subject" leaves it open to apply to an instance of anything we like, so there should be no technical problem to use it in a dwc:Occurrence context or in a dwc:Event context.

The relevant practical question right now is, "Does it make any difference to a data publisher if the term is in the dwc: namespace or the eco: namespace?" I don't think so. It will likely be completely irrelevant to most people. 

If a consensus can be reached that the dwc: term can serve perfectly well in place of the proposed eco: term, we can remove the new term from the proposal and replace it with the dwc: version in the Extension definition. In other words, the Humboldt Extension would still include the identifiedBy term, but would not require a new term to be created to fill this role. 

The same considerations apply equally to the [proposal for eco:identificationReferences](https://github.com/tdwg/hc/issues/57).

**Comment by tucotuco** [comment]
In the Humboldt Extension Task Group meeting today it was agreed that the eco:identifiedBy term need not be created if the dwc:identifiedBy term is included in the extension in its place. However, doing so, The Task Group proposes that an addition be made to the comments of the dwc:identifiedBy term to reflect the use of the term in the Humboldt Extension context. A [new issue to propose that change](https://github.com/tdwg/dwc/issues/492) has been created and should be considered part of the [Humboldt Extension public review milestone](https://github.com/tdwg/hc/milestone/1).
