### ISSUE TITLE
New Term - identificationReferences

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#57]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None
Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): identificationReferences
* Term label (English, not normative): Identification References
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): A list (concatenated and separated) of references (publication, global unique identifier, URI) used in the Identification.
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to separate the values in a list with space vertical bar space ( | ).
* Examples (not normative): `Aves del Noroeste Patagonico. Christie et al. 2004.`; `Stebbins, R. Field Guide to Western Reptiles and Amphibians. 3rd Edition. 2003. | Irschick, D.J. and Shaffer, H.B. (1997). The polytypic species revisited: Morphological differentiation among tiger salamanders (Ambystoma tigrinum) (Amphibia: Caudata). Herpetologica, 53(1), 30-49.`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): DataSets/DataSet/Units/Unit/Identifications/Identification/References

**Comment by nielsklazenga** [comment]
Is this a new term or is it the existing http://rs.tdwg.org/dwc/terms/identificationReferences? Definitions are the same.

**Comment by tucotuco** [comment]
This is anew term in the eco: namespace an applies at the level of a dwc:Event. The same with eco:identifiedBy.

**Comment by tucotuco** [comment]
In the Humboldt Extension Task Group meeting today it was agreed that the eco:identificationReferences term need not be created if the dwc:identificationReferences term is included in the extension in its place. However, doing so, The Task Group proposes that an addition be made to the comments of the dwc:identificationReferences term to reflect the use of the term in the Humboldt Extension context. A [new issue to propose that change](https://github.com/tdwg/dwc/issues/493) has been created and should be considered part of the [Humboldt Extension public review milestone](https://github.com/tdwg/hc/milestone/1).
