### ISSUE TITLE
New Term - compilationTypes

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#58]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Needs ecoiri: equivalent.
Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): compilationTypes
* Term label (English, not normative): Compilation Types
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): A statement specifying whether data reported are derived from sampling events, ancillary data compiled from other sources, or a combination of both.
* Usage comments (recommendations regarding content, etc., not normative): This term is only relevant if the dwc:Event is an inventory. Recommended best practice is to use a controlled vocabulary.
* Examples (not normative): `survey only`; `compilation including surveys`; `compilation not including surveys`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by kingenloff** [comment]
Term name updated from compilationType to compilationTypes following the precedence that plurality should match the content a field can accept.
