### ISSUE TITLE
New Term - protocolDescriptions

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#62]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): Needs ecoiri: equivalent.
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None
Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): protocolDescriptions
* Term label (English, not normative): Protocol Descriptions
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): A detailed description of the methods used during the dwc:Event.
* Usage comments (recommendations regarding content, etc., not normative): This description should be associated with protocols provided in eco:protocolNames. The description may include deviations from a protocol referred to in eco:protocolReferences. Recommended good practice is to provide information about instruments used, calibration, etc.
* Examples (not normative): `Three conventional harp traps (3.2m ht x 2.2m w) were established in flight path zones for a period of 4 hrs at dawn and dusk for a total of 10 trap nights. Traps were visited on an hourly basis during each deployment period and the trap catch recorded for species, size, weight, sex, age and maternal status.`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by kingenloff** [comment]
Term name updated from protocolDescription to protocolDescriptions following the precedence that plurality should match the content a field can accept.
