### ISSUE TITLE
New Term - samplingPerformedBy

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#77]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Needs ecoiri: equivalent.
Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): samplingPerformedBy
* Term label (English, not normative): Sampling Performed By
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): A person, group, or organization responsible for recording the dwc:Event.
* Usage comments (recommendations regarding content, etc., not normative): The sampling dwc:Event could be at any level of hierarchy. In the case of a higher level (parent) dwc:Event, include all the organizations or people involved in the child dwc:Events that contributed to the parent dwc:Event. Recommended best practice is to separate multiple values in a list with space vertical bar space ( | ).
* Examples (not normative): `North American Butterlfy Association`; `KK Wall`; `JJ Green`; `LL Pink and FF Grey | Aspen Center for Environmental Studies`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by MattBlissett** [comment]
There's a minor spelling error in the example, `Butterlfy` not `Butterfly`.
