### ISSUE TITLE
New Term - isSamplingEffortReported

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#78]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Needs ecoiri: equivalent.
Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): isSamplingEffortReported
* Term label (English, not normative): Is Sampling Effort Reported
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): The sampling effort associated with the dwc:Event was reported.
* Usage comments (recommendations regarding content, etc., not normative): Typically values of effort would be captured under the terms eco:samplingEffortValue and eco:samplingEffortUnit.
* Examples (not normative): `true`; `false`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by tucotuco** [comment]
In the Technical Architecture Group meeting on 2023-09-11 it was recommended that the comments for boolean terms include a statement such as, "Recommended best practice is to comply with the recommendations provided in the Boolean Controlled Vocabulary document (https://tag.tdwg.org/boolean/)."

**Comment by kingenloff** [comment]
From our ALA colleagues: 'Terms such as **_isSamplingEffortReported_** seem to be inferable from other terms. And having **_isSamplingEffortReported_**: true and **_samplingEffortValue_** (https://github.com/tdwg/hc/issues/80) empty makes no sense. Why are these terms needed?'
