### ISSUE TITLE
Question around *ID terms for people/agents

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/hc#83]
There has been a lot of interest in disambiguating the person names in the various DwC terms over the last few years. Were `identifiedByID` and `samplingPerformedByID` considered for inclusion with HC, please?

**Comment by tucotuco** [comment]
The following is personal opinion. I think it was a mistake to mint the recordedByID and identifiedByID terms for the simple reason that terms already existed in the dwciri: namespace (dwciri:recordedBy and dwciri:identifiedBy) for the purpose these were minted. The only differences are that the newly minted terms reside in the dwc: namespace and parallel the original non-ID terms in allowing a list of identifiers. I wouldn't want to see the same proliferation happen again without very good cause.

The ecoiri: equivalents of eco:identifiedBy and eco:samplingPerformedBy will be created automatically if these two terms are ratified.

**Comment by timrobertson100** [comment]
Thanks, @tucotuco - that answers the question clearly, so I'll close this.
I think there are implications for the implementations (e.g. DwC-A schemas and GBIF IPT) but that discussion can be had on those repositories.
