### ISSUE TITLE
Multiple Inventories for Different Purposes

### ISSUE THREAD

**Issue by kingenloff** [tdwg/hc#90]
From our ALA colleagues: 'In analysing the extension model we identified three possible uses of inventories:
Statements of intention. This is the scope of what the activity is intended to cover.
Statements of actuality. This is the scope of what the activity has actually covered, based on comparison with a statement of intention.
Statements of description. This is the scope of the data collected.

The current Humboldt extension appears to link statements of intention and actuality into a single record. Term names reflect this, with **targetTaxonomicScope**, rather than **taxonomicScope**.

In some cases, it is hard to determine whether the term refers to an intention or an actual result. For example **eventDuration** could mean either the intended duration or the actual duration taken.

We propose a different way of structuring inventories, with **inventoryType** describing the intended purpose of the inventory. This would involve the following changes: (1) Terms such as **targetTaxonomicScope** would be renamed **taxonomicScope**. Whether the scope is a target, measure of completeness or a description would be dependent on the inventory type. (2) Completeness inventories and description inventories can be linked to target inventories by use of a **targetInventoryID** using the **inventoryID** discussed above.

The changes proposed would allow the presence of descriptive inventories without ambiguity. It would also allow a cleared relationship between intention and actuality; terms such as **hasVouchers** can either represent the intention to collect vouchers or the fact that voucher specimens have been collected.'

**Comment by kingenloff** [comment]
This issue highlights data provider vs data user perspective. The Task Group discussed this concept of intention versus actuality in depth. Ultimately the Task Group agreed that, generally speaking, statements of intention about a dataset are metadata not data; statements of actuality are data. The exception to this are scope terms, which are necessary for interpreting terms of reported completeness.

The Task Group will communicate with ALA to clarify their comments and discuss our position on the terms. We will also clarify (1) terms of intention vs actuality and ensure they are clearly communicated in the user Guide and elsewhere as appropriate/necessary and (2) how this should be used by aggregators.

**Comment by tucotuco** [comment]
@kingenloff Can this issue be closed?
